version: 0.2

phases:
  build:
    commands:
      - echo "Build phase"
        #This command will clean the project and package it into a JAR file
      - mvn clean package

  post_build:
    commands:
      - echo "Test phase"
        #This command will run the unit tests
      - mvn test
        #This command will print a message to the console if the unit tests pass
      - echo "Unit tests passed"
      - echo "Deploying..."

artifacts:
    files:
          #This command will upload the JAR file to the artifacts section of the build
        - target/books-pipeline.jar
    discard-paths: yes
