name: CI/CD pipeline
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  build and test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml